server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurante_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # cria/atualiza tabelas automaticamente
    show-sql: true        # mostra as queries no console
    properties:
      hibernate:
        format_sql: true  # deixa as queries mais legíveis
